FROM golang:1.11.0-alpine3.8 AS build

RUN apk update && apk add git

RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/nokamoto/proposal-nginx-grpc

COPY Gopkg.lock .
COPY Gopkg.toml .
COPY protobuf protobuf
COPY client client

RUN dep ensure -vendor-only=true

RUN go install ./client

FROM alpine:3.8

COPY --from=build /go/bin/client /usr/local/bin/client

ENTRYPOINT [ "top" ]
